name: Push

on:
  workflow_dispatch:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: ~1.22
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Proto format
        run: make check-proto-format

      - name: Test
        run: make test
